"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MultiTimer.py']
DATA_FILES = []
OPTIONS = {
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['PyXA', 'AppKit', 'AVFoundation', 'CoreLocation', 'CoreMedia', 'EventKit', 'NaturalLanguage', 'objc', 'Quartz', 'ScriptingBridge', 'Vision'],
    'excludes': ['tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter', 'ttk', 'tcl8', 'tcl8.6', 'tk8.6'],
    'iconfile': 'assets/MultiTimer.icns',
    'optimize': 2,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    install_requires=['pyobjc'],
    setup_requires=['py2app'],
)
